common: &common
  adapter: postgresql
  host: localhost
  username: coachup_user
  password: coachup_pass # from psql setup, see Postgresql

development:
  <<: *common
  database: coachup_development

test:
  <<: *common
  database: coachup_test

production:
  <<: *common
  database: coachup_production